/**
 * Hierarchy Policy — Domain-Independent Rules.
 *
 * Hierarchy is NEVER directly generated by the LLM.
 * It is derived deterministically from validated relationships.
 */

import type { Relationship, DerivedHierarchyNode } from "../schemas";

// ─── Derivation Rules ───────────────────────────────────────────────────────

/**
 * How hierarchy properties are derived:
 *
 * root: an object with no incoming child_of relationship
 * depth: count of child_of edges from root to object
 * parent: the single object this is child_of (if any)
 * children: objects that have child_of pointing to this
 * siblings: objects sharing the same parent
 * tree: all objects reachable through child_of from the same root
 * forest: collection of all trees
 */
export const HIERARCHY_DERIVATION_RULES = {
  root_detection: "An object with no incoming child_of edge is a root",
  depth_calculation: "depth = number of child_of edges traversed from root",
  parent_selection: "parent = the target of this object's child_of relationship",
  sibling_grouping: "siblings = all objects sharing the same parent",
  tree_membership: "tree = all objects reachable via child_of from one root",
  cross_tree_bridges: "semantic relationships between different trees are bridges, not hierarchy",
} as const;

// ─── Validation Rules (deterministic, non-negotiable) ───────────────────────

/**
 * Validate derived hierarchy for structural integrity.
 */
export function validateHierarchy(
  hierarchy: DerivedHierarchyNode[],
  relationships: Relationship[],
): string[] {
  const violations: string[] = [];

  // Rule 1: No cycles in child_of
  const parentMap = new Map<string, string>();
  for (const rel of relationships) {
    if (rel.type === "child_of" && rel.status !== "removed") {
      parentMap.set(rel.sourceObjectId, rel.targetObjectId);
    }
  }
  for (const [startId] of parentMap) {
    const visited = new Set<string>();
    let current: string | undefined = startId;
    while (current && parentMap.has(current)) {
      if (visited.has(current)) {
        violations.push(`Cycle detected: ${startId} participates in a child_of cycle`);
        break;
      }
      visited.add(current);
      current = parentMap.get(current);
    }
  }

  // Rule 2: diverged_from must NOT create parent-child hierarchy
  for (const rel of relationships) {
    if (rel.type === "diverged_from") {
      const alsoChildOf = relationships.some(
        (r) => r.type === "child_of" && r.sourceObjectId === rel.sourceObjectId && r.targetObjectId === rel.targetObjectId,
      );
      if (alsoChildOf) {
        violations.push(`diverged_from AND child_of between ${rel.sourceObjectId} → ${rel.targetObjectId} is contradictory`);
      }
    }
  }

  // Rule 3: Every hierarchy node must have consistent depth
  for (const node of hierarchy) {
    if (node.parentObjectId === null && node.depth !== 0) {
      violations.push(`Root node ${node.objectId} has non-zero depth: ${node.depth}`);
    }
  }

  // Rule 4: Cross-tree bridges must not merge trees
  // (Trees are identified by root — objects in different trees should not share a tree ID)
  const treeRoots = new Map<string, string>(); // treeId → rootObjectId
  for (const node of hierarchy) {
    if (node.depth === 0) {
      if (treeRoots.has(node.treeId) && treeRoots.get(node.treeId) !== node.objectId) {
        violations.push(`Tree ${node.treeId} has multiple roots`);
      }
      treeRoots.set(node.treeId, node.objectId);
    }
  }

  return violations;
}

// ─── Ambiguity Handling ─────────────────────────────────────────────────────

/**
 * When multiple parents are plausible:
 * - Do NOT guess silently
 * - Preserve candidate relationships with confidence scores
 * - Choose primary parent ONLY when one is clearly dominant (confidence > 0.8)
 * - Otherwise: keep as separate root or flag as unresolved placement
 */
export const AMBIGUITY_HANDLING = {
  multiple_parents: "Flag as ambiguous. Choose primary only if confidence > 0.8. Otherwise separate root.",
  uncertain_depth: "Compute from validated child_of only. Never estimate.",
  unclear_tree_membership: "Unresolved objects become temporary roots until placement is validated.",
} as const;
