/**
 * A suggested semantic edge between two context nodes.
 * Generated by the edge suggestion engine — not yet persisted or rendered.
 */
export type SuggestedEdge = {
  sourceNodeId: string;
  targetNodeId: string;
  similarity: number;
  /** One-sentence LLM explanation of why these nodes are related. */
  explanation: string;
};

/**
 * A persisted semantic edge loaded from the database.
 * These are rendered in React Flow.
 */
export type SemanticEdge = {
  id: string;
  sourceNodeId: string;
  targetNodeId: string;
  relationshipType: string;
  status: "suggested" | "confirmed" | "rejected";
  similarityScore: number;
  explanation: string;
};
